# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
image: "registry.gitlab.com/reckoning/app"

cache:
  key: gems
  paths:
    - vendor/bundle

stages:
  - checks
  # - tests
  # - deploy

.standard_template: &standard_template
  before_script:
    - "bundle check --path=vendor/bundle"
    - "bundle install --path=vendor/bundle --jobs=$(nproc) --retry=3"

audit:
  <<: *standard_template
  script:
    - "bundle exec bundle-audit update"
    - "bundle exec bundle-audit check"
  stage: checks

rubocop:
  <<: *standard_template
  script:
    - "bundle exec rubocop --format progress"
  stage: checks
