language: ruby
sudo: false
rvm:
  - 2.2.2
cache: bundler
before_script:
  - bundle exec thor setup:dev_env
  - bundle exec rake db:setup db:migrate
  - sudo apt-get install -y wkhtmltopdf
branches:
  only:
    - master
    - develop
