language: ruby
rvm:
  - 2.1.0
before_script:
  - cp config/database.example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - cp config/settings.example.yml config/settings.yml
