production:
  adapter: postgresql
  database: reckoning
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  user: <%= ENV["DATABASE_USER"] %>

development:
  adapter: postgresql
  database: reckoning_dev
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  user: <%= ENV["DATABASE_USER"] %>

test:
  adapter: postgresql
  database: reckoning_test
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  user: <%= ENV["DATABASE_USER"] %>
