production:
  url: <%= ENV["DATABASE_URL"] %>

development:
  database: reckoning_dev
  adapter: postgresql
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  database: reckoning_test
  adapter: postgresql
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
