production:
  adapter: postgresql
  database: reckoning
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>

development:
  adapter: postgresql
  database: reckoning_dev
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>

test:
  adapter: postgresql
  database: reckoning_test
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
