production: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  devise: <%= ENV["DEVISE_SECRET"] %>
  devise_jwt: <%= ENV["DEVISE_JWT_SECRET"] %>
  jwt_expiration: <%= 24.hours.to_i %>

  devise_otp: <%= ENV["DEVISE_OTP_SECRET"] %>
  devise_otp_issuer: Reckoning

  ga: <%= ENV["GOOGLE_ANALYTICS"] %>

  registration: <%= ENV["SETTING_REGISTRATION"] %>
  demo: <%= ENV["SETTING_DEMO"] %>

  mailer_default_from: noreply@reckoning.cc
  mailer_host: <%= ENV["SMTP_HOST"] %>
  mailer_port: <%= ENV["SMTP_PORT"] %>
  mailer_user: <%= ENV["SMTP_USER"] %>
  mailer_password: <%= ENV["SMTP_PASSWORD"] %>

  url: <%= ENV["APP_URL"] %>
  domain: <%= ENV["DOMAIN"] %>

  dropbox_key: <%= ENV["DROPBOX_KEY"] %>
  dropbox_secret: <%= ENV["DROPBOX_SECRET"] %>

  sentry_js: <%= ENV["SENTRY_JS"] %>

  google_api_key: 'AIzaSyBKuPSNd8Jo3AEbGBN6WzSzqM2hibS5OHQ'

  s3_key: <%= ENV["S3_KEY"] %>
  s3_secret: <%= ENV["S3_SECRET"] %>
  s3_space: <%= ENV["S3_SPACE"] %>
  s3_region: <%= ENV["S3_REGION"] %>
  s3_endpoint: <%= ENV["S3_ENDPOINT"] %>

  stripe_secret_key: <%= ENV["STRIPE_SECRET"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC"] %>

  recaptcha: <%= ENV["RECAPTCHA_KEY"] %>

development:
  <<: *default

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>

  devise: <%= ENV["DEVISE_SECRET"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>
  devise_jwt: <%= ENV["DEVISE_JWT_SECRET"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>
  devise_otp: <%= ENV["DEVISE_OTP_SECRET"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>

  registration: true
  demo: true

  url: http://reckoning.test
  domain: reckoning.test

test:
  <<: *default
  secret_key_base: secret

  devise: devise
  devise_jwt: devise_jwt
  devise_otp: devise_otp
  devise_otp_issuer: Reckoning

  registration: true
  demo: false

  url: http://reckoning.test
  domain: reckoning.test
