production:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: noreply@reckoning.io
    host:
    port:
    user:
    password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
  intercom:
  stripe:
    secret_key:
    public_key:
development:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: noreply@reckoning.io
    host:
    port:
    user:
    password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
  logentries:
  intercom:
  stripe:
    secret_key:
    public_key:
test:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: noreply@reckoning.io
    host:
    port:
    user:
    password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
  logentries:
  intercom:
  stripe:
    secret_key:
    public_key:
