production:
  secret_key_base: rails_secret_base
  devise: devise_secret
  devise_otp: devise_otp_secret
  devise_otp_issuer: "Reckoning.io"
  sentry: sentry
  ga:
  registration: true
  demo: true
  mailer_default_from: noreply@reckoning.io
  mailer_host:
  mailer_port:
  mailer_user:
  mailer_password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
  stripe_secret_key:
  stripe_public_key:
development:
  secret_key_base: rails_secret_base
  devise: devise_secret
  devise_otp: devise_otp_secret
  devise_otp_issuer: "Reckoning.io"
  sentry: sentry
  ga:
  registration: true
  demo: true
  mailer_default_from: noreply@reckoning.io
  mailer_host:
  mailer_port:
  mailer_user:
  mailer_password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
  stripe_secret_key:
  stripe_public_key:
test:
  secret_key_base: rails_secret_base
  devise: devise_secret
  devise_otp: devise_otp_secret
  devise_otp_issuer: "Reckoning.io"
  sentry: sentry
  ga:
  registration: true
  demo: true
  mailer_default_from: noreply@reckoning.io
  mailer_host:
  mailer_port:
  mailer_user:
  mailer_password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
  stripe_secret_key:
  stripe_public_key:
