<%= ENV["RAILS_ENV"] %>:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_SECRET"] %>
  devise_otp: <%= ENV["DEVISE_OTP_SECRET"] %>
  devise_otp_issuer: Reckoning.io
  ga: <%= ENV["GOOGLE_ANALYTICS"] %>
  base:
    registration: <%= ENV["SETTING_REGISTRATION"] %>
    demo: <%= ENV["SETTING_DEMO"] %>
  mailer:
    default_from: noreply@reckoning.io
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  url: <%= ENV["APP_URL"] %>
  domain: <%= ENV["DOMAIN"] %>
  dropbox_key: <%= ENV["DROPBOX_KEY"] %>
  dropbox_secret: <%= ENV["DROPBOX_SECRET"] %>
  intercom: <%= ENV["INTERCOM"] %>
  sentry_js: <%= ENV["SENTRY_JS"] %>
  stripe:
    secret_key: <%= ENV["STRIPE_SECRET"] %>
    public_key: <%= ENV["STRIPE_PUBLIC"] %>
