production:
  secret_key_base: rails_secret_base
  devise: devise_secret
  devise_otp: devise_otp_secret
  devise_otp_issuer: "Reckoning.io"
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: noreply@reckoning.io
    host:
    port:
    user:
    password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
development:
  secret_key_base: rails_secret_base
  devise: devise_secret
  devise_otp: devise_otp_secret
  devise_otp_issuer: "Reckoning.io"
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: noreply@reckoning.io
    host:
    port:
    user:
    password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
test:
  secret_key_base: rails_secret_base
  devise: devise_secret
  devise_otp: devise_otp_secret
  devise_otp_issuer: "Reckoning.io"
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: noreply@reckoning.io
    host:
    port:
    user:
    password:
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
