production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_SECRET"] %>
  devise_otp: <%= ENV["DEVISE_OTP_SECRET"] %>
  devise_otp_issuer: Reckoning.io
  ga: <%= ENV["GOOGLE_ANALYTICS"] %>
  registration: <%= ENV["SETTING_REGISTRATION"] %>
  demo: <%= ENV["SETTING_DEMO"] %>
  mailer_default_from: noreply@reckoning.io
  mailer_host: <%= ENV["SMTP_HOST"] %>
  mailer_port: <%= ENV["SMTP_PORT"] %>
  mailer_user: <%= ENV["SMTP_USER"] %>
  mailer_password: <%= ENV["SMTP_PASSWORD"] %>
  url: <%= ENV["APP_URL"] %>
  domain: <%= ENV["DOMAIN"] %>
  dropbox_key: <%= ENV["DROPBOX_KEY"] %>
  dropbox_secret: <%= ENV["DROPBOX_SECRET"] %>
  sentry_js: <%= ENV["SENTRY_JS"] %>
  google_api_key: 'AIzaSyBKuPSNd8Jo3AEbGBN6WzSzqM2hibS5OHQ'
  aws_key: <%= ENV["AWS_S3_KEY_ID"] %>
  aws_secret: <%= ENV["AWS_S3_ACCESS_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC"] %>
