test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  bucket: reckoning
  endpoint: https://fra1.digitaloceanspaces.com
  region: fra1
  access_key_id: <%= Rails.application.credentials.dig(:s3_key) %>
  secret_access_key: <%= Rails.application.credentials.dig(:s3_secret) %>
